export const BASE_URL = `http://localhost:5678/`;


export const Video = {
    GET_ALL: "GET_ALL_VIDEOS",
    GET_BY_ID: "GET_VIDEO_BY_ID",
    LOAD_ALL: "LOAD_ALL_VIDEOS",
    LOAD_BY_ID: "LOAD_VIDEO_BY_ID",
    POST: "POST_VIDEO",
    POST_DESCRIPTION: "POST_VIDEO_DESCRIPTION",
    UPDATE: "UPDATE_VIDEO",
    UPDATE_THUMBNAIL: "UPDATE_VIDEO_THUMBNAIL",
    DELETE: "DELETE_VIDEO",
    LOAD_ERROR: "LOAD_VIDEO_ERROR"
}


export const VideoStreaming = {
    GET: "GET_VIDEO",
    STREAM: "STREAM_VIDEO",
    ERROR: "STREAM_ERROR"
}