export const BASE_URL = `http://localhost:5678/`;


export const Video = {
    FETCH_ALL_VIDEOS: "FETCH_ALL_VIDEOS",
    FETCH_ALL_VIDEOS_SUCCESS: "FETCH_ALL_VIDEOS_SUCCESS",
    FETCH_ALL_VIDEOS_FAILURE: "FETCH_ALL_VIDEOS_FAILURE",
    GET_ALL: "GET_ALL_VIDEOS",
    GET_BY_ID: "GET_VIDEO_BY_ID",
    LOAD_ALL: "LOAD_ALL_VIDEOS",
    LOAD_BY_ID: "LOAD_VIDEO_BY_ID",
    POST: "POST_VIDEO",
    POST_DESCRIPTION: "POST_VIDEO_DESCRIPTION",
    UPDATE: "UPDATE_VIDEO",
    UPDATE_THUMBNAIL: "UPDATE_VIDEO_THUMBNAIL",
    DELETE: "DELETE_VIDEO",
    LOAD_ERROR: "LOAD_VIDEO_ERROR"
}


export const VideoStreaming = {
    STREAM_VIDEO_REQUEST: "STREAM_VIDEO_REQUEST",
    STREAM_VIDEO_SUCCESS: "STREAM_VIDEO_SUCCESS",
    STREAM_VIDEO_ERROR: "STREAM_VIDEO_ERROR"
}


export const User = {
    USER_SIGNUP_REQUEST : "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS : "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAILURE : "USER_SIGNUP_FAILURE",
    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE"

}